//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvvisiPagamentoPA
    {
        public long Id { get; set; }
        public System.Guid IdRichiesta { get; set; }
        public string DenominazioneEnte { get; set; }
        public string CFEnte { get; set; }
        public string Settore { get; set; }
        public string Destinatario { get; set; }
        public decimal Importo { get; set; }
        public System.DateTime Scadenza { get; set; }
        public string Cbill { get; set; }
        public string CodiceAvviso { get; set; }
        public string CCPostale { get; set; }
        public Nullable<short> NumeroRate { get; set; }
        public string Data { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
