//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bollettino
    {
        public System.Guid IdBollettino { get; set; }
        public System.Guid IdRichiesta { get; set; }
        public int Pagina { get; set; }
        public string Codice { get; set; }
        public bool Logo { get; set; }
        public string NumeroContoCorrente { get; set; }
        public string IntestatoA { get; set; }
        public string FormatoStampa { get; set; }
        public string Template { get; set; }
        public string AdditionalInfo { get; set; }
        public string NumeroAutorizzazioneStampaInProprio { get; set; }
        public string IBAN { get; set; }
        public string Eseguitoda { get; set; }
        public Nullable<decimal> Importo { get; set; }
        public string Causale { get; set; }
        public string CodiceCliente { get; set; }
        public string Xml { get; set; }
    }
}
