//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOL()
        {
            this.LOLDocumenti = new HashSet<LOLDocumenti>();
            this.LOLDestinatario = new HashSet<LOLDestinatario>();
        }
    
        public System.Guid IdRichiesta { get; set; }
        public string GuidUtente { get; set; }
        public string IdStatoLavorazione { get; set; }
        public string IdDCS { get; set; }
        public string MessageDCS { get; set; }
        public Nullable<int> NumeroDestinatari { get; set; }
        public Nullable<System.DateTime> DataLettera { get; set; }
        public string UriDCS { get; set; }
        public Nullable<bool> InStampa { get; set; }
        public Nullable<bool> ForzaDestinazioniValide { get; set; }
        public Nullable<bool> Scadenza { get; set; }
        public string UriLogo { get; set; }
        public string ClosingLettera { get; set; }
        public string ClosingCover { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<bool> DocPrezzabile { get; set; }
        public Nullable<bool> Estero { get; set; }
        public Nullable<bool> DocStampabile { get; set; }
        public string Hash_MD5 { get; set; }
        public string CodiceNazione { get; set; }
        public Nullable<long> IdSublotto { get; set; }
        public string IdRendicontazione { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> RichiestaTracciatura { get; set; }
        public bool PrezzaturaSincrona { get; set; }
        public bool PrezzaturaSincronaSuccess { get; set; }
        public string IdCover { get; set; }
    
        public virtual LOL LOL1 { get; set; }
        public virtual LOL LOL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOLDocumenti> LOLDocumenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOLDestinatario> LOLDestinatario { get; set; }
    }
}
