//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOLDestinatario
    {
        public System.Guid IdRichiesta { get; set; }
        public string IdLettera { get; set; }
        public string IdDestinatario { get; set; }
        public Nullable<int> NumeroDestinatarioCorrente { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public string ComplementoNominativo { get; set; }
        public string RagioneSociale { get; set; }
        public string DUG { get; set; }
        public string Toponimo { get; set; }
        public string NumeroCivico { get; set; }
        public string Esponente { get; set; }
        public string ComplementoIndirizzo { get; set; }
        public string CAP { get; set; }
        public string Frazione { get; set; }
        public string Citta { get; set; }
        public string Provincia { get; set; }
        public string Stato { get; set; }
        public string Telefono { get; set; }
        public string Zona { get; set; }
        public string TipoIndirizzo { get; set; }
        public string CasellaPostale { get; set; }
        public string UfficioPostale { get; set; }
        public string ProtocolloMittente { get; set; }
        public string TestoLibero { get; set; }
        public string CodiceTracciatura { get; set; }
        public Nullable<System.DateTime> DataAccettazione { get; set; }
        public string Codice2DCOMM { get; set; }
        public Nullable<byte> StatoArchiviazione { get; set; }
        public Nullable<System.DateTime> DataStatoArchiviazione { get; set; }
        public Nullable<long> RichiesteDocumenti { get; set; }
    
        public virtual LOL LOL { get; set; }
    }
}
