//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NPCELOLEntities : DbContext
    {
        public NPCELOLEntities()
            : base("name=NPCELOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOL> LOL { get; set; }
        public virtual DbSet<LOLDestinatario> LOLDestinatario { get; set; }
        public virtual DbSet<LOLDocumenti> LOLDocumenti { get; set; }
    }
}
