//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opzioni
    {
        public System.Guid IdRichiesta { get; set; }
        public string TipoColore { get; set; }
        public bool FronteRetro { get; set; }
        public string ModalitaConsegna { get; set; }
        public bool AttestazioneConsegna { get; set; }
        public bool SecondoTentativoRecapito { get; set; }
        public Nullable<int> AnniArchiviazione { get; set; }
        public bool TipoNomeProprio { get; set; }
        public bool InErogazione { get; set; }
        public bool Nazionale { get; set; }
        public string ModalitaPricing { get; set; }
        public short TipoArchiviazione { get; set; }
    
        public virtual Richieste Richieste { get; set; }
    }
}
