//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Richieste
    {
        public System.Guid IdRichiesta { get; set; }
        public bool AutoConferma { get; set; }
        public string Prodotto { get; set; }
        public System.DateTime DataInvio { get; set; }
        public Nullable<System.DateTime> DataAccettazione { get; set; }
        public Nullable<int> NumeroDestinatari { get; set; }
        public Nullable<bool> RicevutaRitorno { get; set; }
        public string StatoCorrente { get; set; }
        public System.DateTime DataStatoCorrente { get; set; }
        public Nullable<byte> IdOmologazione { get; set; }
        public bool InErogazione { get; set; }
        public string ConversionMessage { get; set; }
        public string CodiceContratto { get; set; }
        public string ConversionURI { get; set; }
        public Nullable<int> NumFogli { get; set; }
        public string ChargingMessage { get; set; }
        public string CIG { get; set; }
        public Nullable<System.DateTime> DataConferma { get; set; }
        public string StatoConsumo { get; set; }
        public Nullable<System.DateTime> DataTracciatura { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string HashMD5 { get; set; }
        public string BollettiniConversion { get; set; }
        public string CIG_Service { get; set; }
        public string CodiceFiscaleCliente { get; set; }
        public string PartitaIvaCliente { get; set; }
        public string RagioneSocialeCliente { get; set; }
        public Nullable<System.Guid> IdLotto { get; set; }
        public Nullable<int> IdentificativoInvioNelLotto { get; set; }
        public string IdCover { get; set; }
    
        public virtual Richieste Richieste1 { get; set; }
        public virtual Richieste Richieste2 { get; set; }
        public virtual Opzioni Opzioni { get; set; }
    }
}
