//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLDestinatarioConversione
    {
        public System.Guid IdRichiesta { get; set; }
        public string IdRaccomandata { get; set; }
        public string Uri { get; set; }
        public string HashMD5 { get; set; }
        public Nullable<int> Size { get; set; }
        public string Message { get; set; }
    }
}
