//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLDCSResponse
    {
        public System.Guid IdRichiesta { get; set; }
        public string DCSResponse { get; set; }
        public System.DateTime Data { get; set; }
    }
}
