//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NPCEROLEntities : DbContext
    {
        public NPCEROLEntities()
            : base("name=NPCEROLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvvisiPagamentoPA> AvvisiPagamentoPA { get; set; }
        public virtual DbSet<Bollettino> Bollettino { get; set; }
        public virtual DbSet<Cover> Cover { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<ROLDCSResponse> ROLDCSResponse { get; set; }
        public virtual DbSet<ROLDestinatarioConversione> ROLDestinatarioConversione { get; set; }
        public virtual DbSet<ROLDocumenti> ROLDocumenti { get; set; }
        public virtual DbSet<ROLOpzioni> ROLOpzioni { get; set; }
        public virtual DbSet<ROLOpzioniAggiuntiveStampa> ROLOpzioniAggiuntiveStampa { get; set; }
        public virtual DbSet<ROLRicevuta> ROLRicevuta { get; set; }
    }
}
