//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPCE.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLRicevuta
    {
        public System.Guid IdRichiesta { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public string ComplementoNominativo { get; set; }
        public string RagioneSociale { get; set; }
        public string DUG { get; set; }
        public string Toponimo { get; set; }
        public string NumeroCivico { get; set; }
        public string Esponente { get; set; }
        public string ComplementoIndirizzo { get; set; }
        public string CAP { get; set; }
        public string Frazione { get; set; }
        public string Citta { get; set; }
        public string Provincia { get; set; }
        public string Stato { get; set; }
        public string Telefono { get; set; }
        public string Zona { get; set; }
        public string TipoIndirizzo { get; set; }
        public string CasellaPostale { get; set; }
        public string UfficioPostale { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
